baseURL = "https://www.caomeisusu.com/"
languageCode = "en-us"

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
copyrighthtml = "&copy; 2022 Dr. Luo Siqiang's Research Group. All rights reserved."
address = "50 Nanyang Ave, #32 Block N4 #02a, Singapore 639798"
twitter_card_format = "summary"

# Date and time formatting, see https://gohugo.io/functions/format/
time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
time_format_RFC822 = "Mon, 02 Jan 2006 15:04:05 -0700"
time_format_default = "Jan 2, 2006"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark]
[markup.goldmark.extensions]
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
# To keep ยง ids identical after the migration from blackfriday to goldmark
autoHeadingIDType = "blackfriday"

[languages]
[languages.en]
title = "Siqiang Luo | Siqiang Luo's Homepage"
languageName ="English"
# Weight used for sorting.
weight = 1
description = """
  ISRG&rsquo;s mission is to reduce financial, technological, and educational barriers to secure communication over the Internet.
"""
