[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.104.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/docs/memory-safety"
  to = "https://www.memorysafety.org/docs/memory-safety"
  status = 301
  force = false

[[redirects]]
  from = "/divviup"
  to = "https://divviup.org"
  status = 301
  force = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false

